/*
 * APIs
 * An example application with OpenAPI, Swashbuckle, and API versioning.
 *
 * OpenAPI spec version: 1.0
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.6.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/v1/identity/register-user", () => {

        // Request No. 1: RegisterUser
        {
            let url = BASE_URL + `/api/v1/identity/register-user`;
            // TODO: edit the parameters of the request body.
            let body = {"firstName": "string", "lastName": "string", "username": "string", "email": "string", "password": "string", "confirmPassword": "string", "passportNumber": "string"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

}
