<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Woo.Web</RootNamespace><AssemblyName>Woo.Web</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Utils\Woo.Utils.csproj" />
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.1" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>
</Project>