<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Woo.Jwt</RootNamespace><AssemblyName>Woo.Jwt</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Woo.Core.csproj" />
    <ProjectReference Include="..\Web\Woo.Web.csproj" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.4.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
  </ItemGroup>
</Project>