<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Woo.Caching</RootNamespace>
    <AssemblyName>Woo.Caching</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EasyCaching.Core" Version="1.9.2" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
  </ItemGroup>
</Project>