<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Woo.Core</RootNamespace><AssemblyName>Woo.Core</AssemblyName></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="Grpc.Core.Testing" Version="2.46.6" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="NewId" Version="4.0.1" />
    <PackageReference Include="Sieve" Version="2.5.5" />
  </ItemGroup>
</Project>