<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Woo.HealthCheck</RootNamespace><AssemblyName>Woo.HealthCheck</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EFCore\Woo.EFCore.csproj" />
    <ProjectReference Include="..\EventStoreDB\Woo.EventStoreDB.csproj" />
    <ProjectReference Include="..\Mongo\Woo.Mongo.csproj" />
    <ProjectReference Include="..\Web\Woo.Web.csproj" />
    <ProjectReference Include="..\Wolverine\Woo.Wolverine.csproj" />
    <PackageReference Include="AspNetCore.HealthChecks.EventStore" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.3" />
  </ItemGroup>
</Project>