<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Woo.TestBase</RootNamespace><AssemblyName>Woo.TestBase</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Woo.Core.csproj" />
    <ProjectReference Include="..\EFCore\Woo.EFCore.csproj" />
    <ProjectReference Include="..\Mongo\Woo.Mongo.csproj" />
    <ProjectReference Include="..\Web\Woo.Web.csproj" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.4.5" />
    <PackageReference Include="EasyNetQ.Management.Client" Version="3.0.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.3" />
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Respawn" Version="7.0.0" />
    <PackageReference Include="Testcontainers.EventStoreDb" Version="4.9.0" />
    <PackageReference Include="Testcontainers.MongoDb" Version="4.9.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.9.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.9.0" />
    <PackageReference Include="WebMotions.Fake.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="WolverineFx" Version="6.16.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="Xunit.Extensions.Logging" Version="1.1.0" />
  </ItemGroup>
</Project>