<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>Woo.EventStoreDB</RootNamespace><AssemblyName>Woo.EventStoreDB</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Woo.Core.csproj" />
    <ProjectReference Include="..\Utils\Woo.Utils.csproj" />
    <ProjectReference Include="..\Web\Woo.Web.csproj" />
    <PackageReference Include="EventStore.Client.Grpc.Streams" Version="23.3.9" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>