/*
 * APIs
 * An example application with OpenAPI, Swashbuckle, and API versioning.
 *
 * OpenAPI spec version: 1.0
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 6.6.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/api/v1/passenger/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1: GetPassengerById
        {
            let url = BASE_URL + `/api/v1/passenger/${id}`;
            let request = http.get(url);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

    group("/api/v1/passenger/complete-registration", () => {

        // Request No. 1: CompleteRegisterPassenger
        {
            let url = BASE_URL + `/api/v1/passenger/complete-registration`;
            // TODO: edit the parameters of the request body.
            let body = {"passportNumber": "string", "passengerType": "passengertype", "age": "integer"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "application/json"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "Success": (r) => r.status === 200
            });
        }
    });

}
